src/Entity/CommerceQuartier.php
<?php

namespace App\Entity;

use App\Repository\CommerceQuartierRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommerceQuartierRepository::class)
 */
class CommerceQuartier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_path;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->img_path;
    }

    public function setImgPath(?string $img_path): self
    {
        $this->img_path = $img_path;

        return $this;
    }
}

src/Entity/Report.php
<?php

namespace App\Entity;

use App\Repository\ReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\CommerceQuartier;
use App\Entity\Doleances;
use App\Entity\Evenement;
use App\Entity\ImportPdf;
use App\Entity\ImportPhoto;
use App\Entity\Report;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        $commerce = $this->getDoctrine()
        ->getRepository(CommerceQuartier::class)
        ->findAll();
    //dd($commerce);
    
    $doleance = $this->getDoctrine()
        ->getRepository(Doleances::class)
        ->findAll();
    //dd($doleance);

    $evenement = $this->getDoctrine()
        ->getRepository(Evenement::class)
        ->findAll();
    //dd($evenement);

    $rapport = $this->getDoctrine()
        ->getRepository(Report::class)
        ->findAll();
    //dd($rapport);

    $gazette = $this->getDoctrine()
        ->getRepository(ImportPdf::class)
        ->findAll();
    //dd($gazette);

    $photo = $this->getDoctrine()
        ->getRepository(ImportPhoto::class)
        ->findAll();
    //dd($photo);

    return $this->render('home/index.html.twig', [
        'evenement' => $evenement,
        'commerce' => $commerce,
        'doleance' => $doleance,
        'rapport' => $rapport,
        'gazette' => $gazette,
        'photo' => $photo
    ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Acceuil
{% endblock %}

{% block content %}
      <!-- Parralax de la page d'acceuil  -->
<div class="parallax-container">
  <div class="parallax">
    <img src="img/image0.jpg"></div>
  </div>
    <div class="row container "> 
        <!-- Présentation du comité de quartier -->
        <div class="col s12 l9">
          <h2 class="header">
            Notre comité
          </h2>
          <p>
            Nous sommes disponibles pour entendre vos remarques et propositions sur la vie du quartier et pour l'amélioration du quotidien et du vivre-ensemble. 
            26 quartiers composent le territoire d'Amiens. Chacun de ces quartiers est représenté par un comité de quartier, structure associative ouverte à tous les résidents.
            <br><br>
            Les comités de quartier sont le relais des demandes des habitants et sont un partenaire privilégié de la municipalité par leur connaissance approfondie de leur secteur.
            Ce sont nos adhérents qui font la force du comité et qui permettent de faire face aux enjeux de notre quartier. 
            Plus nous serons nombreux, plus la voix des habitants pourra se faire entendre ! 
            Votre soutien est primordial ! Aidez-nous à rendre le quartier dynamique et animé !
          </p>
        </div>
        <!-- Illustration comité de quartier (libre de droit) -->
        <div class="col s12 l3">
            <img class="responsive-img" src="img/img-index1.svg" width="100%">
        </div>
    
  </div>
        <!-- Carousel des commerces du quartier -->
   <div class="carousel carousel-slider center">
    {% for commerce in commerce %}    
      <div class="carousel-item" href="#{{commerce.id}}!">
        <h2>{{commerce.name}}</h2>
        <p class="">{{commerce.description}}</p>
        <p>{{commerce.address}}</p>
        <p>{{commerce.imgpath}}</p>
      </div>
    {% endfor %}
  </div>
    <!-- Topic à propos du quartier -->
    <div class="row">
      <div class="container light-green lighten-3">
        <div class="col s12 l4 card-panel teal lighten-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui nihil soluta porro adipisci nostrum veniam. Quisquam unde eligendi exercitationem aliquid deserunt ratione delectus ipsa at! Optio laborum aperiam repudiandae mollitia?</div>
        <div class="col s12 l4 card-panel teal lighten-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui nihil soluta porro adipisci nostrum veniam. Quisquam unde eligendi exercitationem aliquid deserunt ratione delectus ipsa at! Optio laborum aperiam repudiandae mollitia?</div>
        <div class="col s12 l4 card-panel teal lighten-2">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui nihil soluta porro adipisci nostrum veniam. Quisquam unde eligendi exercitationem aliquid deserunt ratione delectus ipsa at! Optio laborum aperiam repudiandae mollitia?</div>
      </div>
    </div>

    






  </div>
{% endblock %}